language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - sudo apt-get update > /dev/null

  # Build Behat dependencies
  - composer install
  - cp behat.local.yml.example behat.local.yml

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null 2>&1 &
  - sleep 5

before_script:

script:

  - ./bin/behat
